-- MySQL Script generated by MySQL Workbench
-- 05/21/17 03:05:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema massage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema massage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `massage` DEFAULT CHARACTER SET utf8 ;
USE `massage` ;

-- -----------------------------------------------------
-- Table `massage`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户名',
  `tel` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户手机号',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
  `affiliation_id` INT UNSIGNED NOT NULL COMMENT '手机号归属地ID',
  `region_id` INT UNSIGNED NOT NULL COMMENT '地区ID',
  `openid` VARCHAR(100) NULL DEFAULT '' COMMENT '微信用户的openid',
  `picture_id` INT UNSIGNED NOT NULL COMMENT '图片ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  INDEX `fk_user_affiliation1_idx` (`affiliation_id` ASC),
  INDEX `fk_user_region1_idx` (`region_id` ASC),
  UNIQUE INDEX `openid_UNIQUE` (`openid` ASC),
  INDEX `fk_user_picture1_idx` (`picture_id` ASC),
  CONSTRAINT `fk_user_affiliation1`
    FOREIGN KEY (`affiliation_id`)
    REFERENCES `massage`.`affiliation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `massage`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `massage`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户表';

-- -----------------------------------------------------
-- Table `massage`.`affiliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`affiliation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '手机号归属地信息ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '手机号归属地名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '手机号码归属地列表';


-- -----------------------------------------------------
-- Table `massage`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`region` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '地址信息自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '地址名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '省市县镇列表';


-- -----------------------------------------------------
-- Table `massage`.`picture_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`picture_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片种类ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '图片种类名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '图片类型列表';


-- -----------------------------------------------------
-- Table `massage`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`picture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片ID',
  `path` TEXT NOT NULL COMMENT '图片路径',
  `picture_type_id` INT UNSIGNED NOT NULL COMMENT '图片种类',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_picture_picture_type1_idx` (`picture_type_id` ASC),
  CONSTRAINT `fk_picture_picture_type1`
    FOREIGN KEY (`picture_type_id`)
    REFERENCES `massage`.`picture_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '图片列表';


-- -----------------------------------------------------
-- Table `massage`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户名',
  `tel` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户手机号',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
  `affiliation_id` INT UNSIGNED NOT NULL COMMENT '手机号归属地ID',
  `region_id` INT UNSIGNED NOT NULL COMMENT '地区ID',
  `openid` VARCHAR(100) NULL DEFAULT '' COMMENT '微信用户的openid',
  `picture_id` INT UNSIGNED NOT NULL COMMENT '图片ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  INDEX `fk_user_affiliation1_idx` (`affiliation_id` ASC),
  INDEX `fk_user_region1_idx` (`region_id` ASC),
  UNIQUE INDEX `openid_UNIQUE` (`openid` ASC),
  INDEX `fk_user_picture1_idx` (`picture_id` ASC),
  CONSTRAINT `fk_user_affiliation1`
    FOREIGN KEY (`affiliation_id`)
    REFERENCES `massage`.`affiliation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `massage`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `massage`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `massage`.`age`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`age` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '年龄段信息ID',
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '年龄段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '年龄段列表';


-- -----------------------------------------------------
-- Table `massage`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`experience` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '经验年段ID',
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '经验年段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `experiencecol_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '经验年段列表';


-- -----------------------------------------------------
-- Table `massage`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`skill` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '技师技能ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '技能名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '技能列表';


-- -----------------------------------------------------
-- Table `massage`.`technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`technician` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '技师自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '技师姓名',
  `tel` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '技师手机号',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '技师密码',
  `sum` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '接单总数',
  `gender` ENUM('女', '男') NOT NULL DEFAULT '女' COMMENT '技师性别',
  `native_place` TEXT NOT NULL COMMENT '技师籍贯',
  `idcard` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '技师身份证号',
  `age_id` INT NOT NULL COMMENT '技师年龄所属阶段ID',
  `age` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '技师年龄',
  `experience` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '技师的经验,单位,年',
  `experience_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '技师经验的年段ID',
  `skill_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '技能ID',
  `region_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '地区ID',
  `picture_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '照片ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC),
  INDEX `fk_technician_age1_idx` (`age_id` ASC),
  UNIQUE INDEX `experience_UNIQUE` (`experience` ASC),
  INDEX `fk_technician_experience1_idx` (`experience_id` ASC),
  INDEX `fk_technician_skill1_idx` (`skill_id` ASC),
  INDEX `fk_technician_region1_idx` (`region_id` ASC),
  INDEX `fk_technician_picture1_idx` (`picture_id` ASC),
  CONSTRAINT `fk_technician_age1`
    FOREIGN KEY (`age_id`)
    REFERENCES `massage`.`age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_experience1`
    FOREIGN KEY (`experience_id`)
    REFERENCES `massage`.`experience` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `massage`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `massage`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `massage`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '技师信息列表';


-- -----------------------------------------------------
-- Table `massage`.`grogshop_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`grogshop_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '酒店负责人ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店负责人姓名',
  `idcard` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店负责人身份证号',
  `picture_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '照片ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC),
  INDEX `fk_grogshop_user_picture1_idx` (`picture_id` ASC),
  CONSTRAINT `fk_grogshop_user_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `massage`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '酒店负责人列表';


-- -----------------------------------------------------
-- Table `massage`.`grogshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`grogshop` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '酒店信息自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店名称',
  `tel` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店手机号',
  `fixedtel` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店固定电话',
  `affiliation_id` INT UNSIGNED NOT NULL COMMENT '酒店手机号归属地',
  `openid` VARCHAR(100) NULL DEFAULT '' COMMENT '酒店微信号openid',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '酒店账号的密码',
  `region_id` INT UNSIGNED NOT NULL COMMENT '酒店粗略地址ID',
  `address` TEXT NOT NULL COMMENT '酒店详细地址',
  `picture_id` INT UNSIGNED NOT NULL COMMENT '酒店相关照片',
  `grogshop_user_id` INT UNSIGNED NOT NULL COMMENT '酒店负责人ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  UNIQUE INDEX `fixedtel_UNIQUE` (`fixedtel` ASC),
  INDEX `fk_grogshop_affiliation1_idx` (`affiliation_id` ASC),
  UNIQUE INDEX `openid_UNIQUE` (`openid` ASC),
  INDEX `fk_grogshop_region1_idx` (`region_id` ASC),
  INDEX `fk_grogshop_picture1_idx` (`picture_id` ASC),
  INDEX `fk_grogshop_grogshop_user1_idx` (`grogshop_user_id` ASC),
  CONSTRAINT `fk_grogshop_affiliation1`
    FOREIGN KEY (`affiliation_id`)
    REFERENCES `massage`.`affiliation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grogshop_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `massage`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grogshop_picture1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `massage`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grogshop_grogshop_user1`
    FOREIGN KEY (`grogshop_user_id`)
    REFERENCES `massage`.`grogshop_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '酒店信息列表';


-- -----------------------------------------------------
-- Table `massage`.`indent_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`indent_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单状态ID',
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '订单状态名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '订单状态信息';


-- -----------------------------------------------------
-- Table `massage`.`indent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`indent` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单信息自增长ID',
  `technician_id` INT UNSIGNED NOT NULL COMMENT '技师ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '客户ID',
  `address` TEXT NOT NULL COMMENT '详细地址',
  `addtime` INT UNSIGNED NOT NULL COMMENT '下单时间',
  `indent_type_id` INT UNSIGNED NOT NULL COMMENT '订单状态ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_indent_technician1_idx` (`technician_id` ASC),
  INDEX `fk_indent_user1_idx` (`user_id` ASC),
  INDEX `fk_indent_indent_type1_idx` (`indent_type_id` ASC),
  CONSTRAINT `fk_indent_technician1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `massage`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indent_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `massage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indent_indent_type1`
    FOREIGN KEY (`indent_type_id`)
    REFERENCES `massage`.`indent_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '订单列表';


-- -----------------------------------------------------
-- Table `massage`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  `name` VARCHAR(100) NOT NULL COMMENT '项目名称',
  `duration` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '服务时长',
  `cost` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '收费价格',
  `intro` TEXT NOT NULL COMMENT '项目简介',
  `part` TEXT NOT NULL COMMENT '针对部位',
  `effect` TEXT NOT NULL COMMENT '预期效果',
  `notice` TEXT NOT NULL COMMENT '预约须知',
  `technician_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_item_technician1_idx` (`technician_id` ASC),
  CONSTRAINT `fk_item_technician1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `massage`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '项目列表';


-- -----------------------------------------------------
-- Table `massage`.`discuss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`discuss` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `message` TEXT NOT NULL COMMENT '评论信息',
  `level` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论星级',
  `technician_id` INT UNSIGNED NOT NULL COMMENT '技师ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_discuss_technician1_idx` (`technician_id` ASC),
  INDEX `fk_discuss_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_discuss_technician1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `massage`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discuss_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `massage`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '评论信息列表';


-- -----------------------------------------------------
-- Table `massage`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massage`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '管理员信息自增长ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '管理员账号',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '管理员密码',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '后台管理员列表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
